<?php

/**
 * H5PLTI Content.
 */

define('H5P_VIDEO_TEMPLATE_NID', 3);

/**
 * Implements hook_views_api().
 */
function h5plti_content_views_api($module = NULL, $api = NULL) {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'h5plti_content'),
    'template path' => drupal_get_path('module', 'h5plti_content'),
  );
}

/**
 * Implements hook_views_pre_render().
 */
function h5plti_content_views_pre_render(&$view) {
  if ($view->name == 'h5p_videos') {
    // Stylize the table.
    $path = drupal_get_path('module', 'h5plti_content');
    drupal_add_css($path . '/css/h5p_videos.css');
  }
}

/**
 * Implements hook_views_query_alter().
 */
function h5plti_content_views_query_alter(&$view, &$query) {
  if ($view->name == 'h5p_videos') {
    // Exclude the template from results.
    foreach ($view->query->where as $key1 => $value1) {
      foreach ($value1['conditions'] as $key2 => $value2) {
        if ($value2['field'] == 'h5p_nodes.content_id' && $value2['value'] == 0) {
          $view->query->where[$key1]['conditions'][$key2]['value'] = H5P_VIDEO_TEMPLATE_NID;
        }
      }
    }
  }
}

/**
 * Implements hook_permission().
 */
function h5plti_content_permission() {
  $items = array();

  $items['view my list with h5p videos'] = array(
    'title' => t('View my list with h5p videos'),
    'description' => t('View the block with list of my h5p videos'),
  );

  $items['add h5p video'] = array(
    'title' => t('Add H5P video'),
    'description' => t('Adding the interactive content with h5p video'),
  );

  $items['edit h5p videos'] = array(
    'title' => t('Edit H5P videos'),
    'description' => t('Edit any h5p video'),
  );

  $items['edit my own h5p videos'] = array(
    'title' => t('Edit my own h5p videos'),
    'description' => t(''),
  );

  $items['del h5p videos'] = array(
    'title' => t('Del H5P videos'),
    'description' => t('Delete any h5p video'),
  );

  $items['del my own h5p videos'] = array(
    'title' => t('Delete my own h5p videos'),
    'description' => t(''),
  );

  return $items;
}

/**
 * Implements hook_menu().
 */
function h5plti_content_menu() {
  $path = drupal_get_path('module', 'h5plti_content');

  $items = array();

  $items['h5p-video/add'] = array(
    'title' => 'Add H5P video',
    'description' => 'Adding the interactive content with h5p video',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('h5plti_h5p_add_form'),
    'access arguments' => array('add h5p video'),
    'file' => 'h5plti_content.add_form.inc',
    'file path' => $path,
  );

  $items['h5p-video/%/edit'] = array(
    'title' => 'Edit H5P video',
    'description' => 'Editing the interactive h5p video',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('h5plti_h5p_edit_form', 1),
    'access callback' => 'h5plti_content_menu_access_edit',
    'access arguments' => array(1),
    'file' => 'h5plti_content.edit_form.inc',
    'file path' => $path,
  );

  $items['h5p-video/%/credentials'] = array(
    'title' => 'LTI credentials for H5P video',
    'description' => 'Get the lti credentials for interactive h5p video',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'h5plti_h5p_credentials',
    'page arguments' => array(1),
    'access callback' => 'h5plti_content_menu_access_edit',
    'access arguments' => array(1),
    'file' => 'h5plti_content.credentials.inc',
    'file path' => $path,
  );

  $items['h5p-video/%/del'] = array(
    'title' => 'Delete H5P video',
    'description' => 'Deleting the interactive h5p video',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'h5plti_h5p_del',
    'page arguments' => array(1),
    'access callback' => 'h5plti_content_menu_access_del',
    'access arguments' => array(1),
    'file' => 'h5plti_content.del.inc',
    'file path' => $path,
  );

  return $items;
}

/**
 * Edit access callback.
 */
function h5plti_content_menu_access_edit($nid) {
  global $user;
  $node = node_load($nid);

  if (user_access('edit h5p videos')) {
    return TRUE;
  }
  else if ($node->uid == $user->uid &&
      user_access('edit my own h5p videos')) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Delete access callback.
 */
function h5plti_content_menu_access_del($nid) {
  global $user;
  $node = node_load($nid);

  if (user_access('del h5p videos')) {
    return TRUE;
  }
  else if ($node->uid == $user->uid &&
      user_access('del my own h5p videos')) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_theme().
 */
function h5plti_content_theme() {
  $items = array();

  $items['h5plti_credentials'] = array(
    'variables' => array('url' => NULL, 'key' => NULL, 'secret' => NULL),
    'template' => 'credentials',
    'path' => drupal_get_path('module', 'h5plti_content') . '/templates',
  );

  return $items;
}
